# Generated by Django 4.2.7 on 2023-12-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('HI', 'Hindi'), ('EN', 'English'), ('MT', 'Math'), ('SC', 'Science'), ('GO', 'Geography')], default='HI', max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_list.student')),
            ],
        ),
    ]
