# Generated by Django 4.2.7 on 2023-12-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0002_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='year_in_school',
            new_name='subject_in_school',
        ),
    ]
